# Generated by Django 3.0.7 on 2020-06-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_link', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('rank', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'PopularMovies',
            },
        ),
    ]
