# Generated by Django 3.0.7 on 2020-06-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularmovie',
            name='rating',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='popularmovie',
            name='rank',
            field=models.CharField(max_length=5),
        ),
    ]
