# Generated by Django 3.0.7 on 2020-06-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200621_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_link', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('rank', models.CharField(max_length=5)),
                ('rating', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'TopMovies',
            },
        ),
    ]
