# Generated by Django 3.0.7 on 2020-06-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_topmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularmovie',
            name='netflix_url',
            field=models.CharField(default='#', max_length=120),
        ),
        migrations.AddField(
            model_name='topmovie',
            name='netflix_url',
            field=models.CharField(default='#', max_length=120),
        ),
    ]
