# Generated by Django 3.0.7 on 2020-06-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200622_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='imdbPopularMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_link', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('rank', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('netflix_url', models.CharField(default='#', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'PopularMovies',
            },
        ),
        migrations.CreateModel(
            name='imdbTopMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_link', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('rank', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('netflix_url', models.CharField(default='#', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'TopMovies',
            },
        ),
        migrations.DeleteModel(
            name='PopularMovie',
        ),
        migrations.DeleteModel(
            name='TopMovie',
        ),
    ]
