# Generated by Django 3.0.7 on 2020-06-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200625_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='imdbPopTv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_link', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('rank', models.CharField(max_length=5)),
                ('imdb_rating', models.CharField(max_length=10)),
                ('netflix_url', models.CharField(default='#', max_length=500)),
                ('country', models.CharField(default='#', max_length=750)),
            ],
            options={
                'verbose_name_plural': 'PopTvs',
            },
        ),
        migrations.CreateModel(
            name='imdbTopTv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_link', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('rank', models.CharField(max_length=5)),
                ('imdb_rating', models.CharField(max_length=10)),
                ('netflix_url', models.CharField(default='#', max_length=500)),
                ('country', models.CharField(default='#', max_length=750)),
            ],
            options={
                'verbose_name_plural': 'TopTvs',
            },
        ),
        migrations.AlterField(
            model_name='imdbpopularmovie',
            name='country',
            field=models.CharField(default='#', max_length=750),
        ),
        migrations.AlterField(
            model_name='imdbpopularmovie',
            name='imdb_rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='imdbpopularmovie',
            name='poster_link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='imdbpopularmovie',
            name='rank',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='imdbtopmovie',
            name='country',
            field=models.CharField(default='#', max_length=750),
        ),
        migrations.AlterField(
            model_name='imdbtopmovie',
            name='imdb_rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='imdbtopmovie',
            name='poster_link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='imdbtopmovie',
            name='rank',
            field=models.CharField(max_length=5),
        ),
    ]
