# Generated by Django 3.0.7 on 2020-06-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200629_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdbpopmovie',
            name='release_date',
            field=models.CharField(default='#', max_length=750),
        ),
        migrations.AddField(
            model_name='imdbpoptv',
            name='release_date',
            field=models.CharField(default='#', max_length=750),
        ),
        migrations.AddField(
            model_name='imdbtopmovie',
            name='release_date',
            field=models.CharField(default='#', max_length=750),
        ),
        migrations.AddField(
            model_name='imdbtoptv',
            name='release_date',
            field=models.CharField(default='#', max_length=750),
        ),
    ]
