# Generated by Django 3.0.7 on 2020-06-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200629_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imdbpopmovie',
            options={'verbose_name_plural': 'PopularMovies'},
        ),
    ]
