# Generated by Django 3.0.7 on 2020-07-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20200629_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdbpopmovie',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imdbpopmovie',
            name='release_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imdbpoptv',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imdbpoptv',
            name='release_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imdbtopmovie',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imdbtopmovie',
            name='release_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imdbtoptv',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imdbtoptv',
            name='release_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
