# Generated by Django 3.0.7 on 2020-07-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200701_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdbpopmovie',
            name='meta_rating',
            field=models.CharField(default='#', max_length=10),
        ),
        migrations.AddField(
            model_name='imdbpopmovie',
            name='rotten_rating',
            field=models.CharField(default='#', max_length=10),
        ),
        migrations.AddField(
            model_name='imdbpopmovie',
            name='trailer_url',
            field=models.CharField(default='#', max_length=750),
        ),
        migrations.AddField(
            model_name='imdbpoptv',
            name='meta_rating',
            field=models.CharField(default='#', max_length=10),
        ),
        migrations.AddField(
            model_name='imdbpoptv',
            name='rotten_rating',
            field=models.CharField(default='#', max_length=10),
        ),
        migrations.AddField(
            model_name='imdbpoptv',
            name='trailer_url',
            field=models.CharField(default='#', max_length=750),
        ),
        migrations.AddField(
            model_name='imdbtopmovie',
            name='meta_rating',
            field=models.CharField(default='#', max_length=10),
        ),
        migrations.AddField(
            model_name='imdbtopmovie',
            name='rotten_rating',
            field=models.CharField(default='#', max_length=10),
        ),
        migrations.AddField(
            model_name='imdbtopmovie',
            name='trailer_url',
            field=models.CharField(default='#', max_length=750),
        ),
        migrations.AddField(
            model_name='imdbtoptv',
            name='meta_rating',
            field=models.CharField(default='#', max_length=10),
        ),
        migrations.AddField(
            model_name='imdbtoptv',
            name='rotten_rating',
            field=models.CharField(default='#', max_length=10),
        ),
        migrations.AddField(
            model_name='imdbtoptv',
            name='trailer_url',
            field=models.CharField(default='#', max_length=750),
        ),
        migrations.AlterField(
            model_name='imdbpopmovie',
            name='imdb_rating',
            field=models.CharField(default='#', max_length=10),
        ),
        migrations.AlterField(
            model_name='imdbpoptv',
            name='imdb_rating',
            field=models.CharField(default='#', max_length=10),
        ),
        migrations.AlterField(
            model_name='imdbtopmovie',
            name='imdb_rating',
            field=models.CharField(default='#', max_length=10),
        ),
        migrations.AlterField(
            model_name='imdbtoptv',
            name='imdb_rating',
            field=models.CharField(default='#', max_length=10),
        ),
    ]
